version: 1.0.{build}
platform: 
- x64
- x86
image: Visual Studio 2019
configuration: Release
init:
- if "%PLATFORM%"=="x64" ( set arch="x64" )
- if "%PLATFORM%"=="x86" ( set arch="Win32" )
- echo %arch%
install:
- git submodule update --init --recursive
before_build:
- cmd: |-
    cmake ./ -G "Visual Studio 16 2019" -A %arch%
build:
  project: WinK760.sln
  parallel: true
  verbosity: normal
after_build:
- cmd: 7z a WinK760-$(platform).zip %APPVEYOR_BUILD_FOLDER%\Release\WinK760.exe
artifacts:
- path: WinK760-$(platform).zip
  name: WinK760-$(platform)
deploy:
- provider: GitHub
  auth_token:
    secure: a/eMX85I7Kw+Mk4vfjfg5pN+jMqjfq4hXr3/JxIDeqcp+s+3iWV+r/TwUVQRSxAj
  artifact: WinK760-$(platform)
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
branches:
  only:
  - master